{{--
    Thin wrapper around <img srcset sizes>, falling back to a plain gray
    box when there's no image at all (a product/category with nothing
    uploaded yet). `srcset`/`sizes` let the *browser* — not the server —
    decide which of the WebP variants generated by App\Services\
    ResponsiveImage to actually download, based on its real viewport and
    pixel density; `sizes` has to describe how big the image actually
    renders in *this* particular layout (a 3-column grid needs a
    different value than a full-bleed hero), so callers always pass it
    explicitly rather than this component guessing.

    `eager` defaults to false (loading="lazy") — set it to true only for
    an image that's visible without scrolling (the main product photo, a
    hero banner), where lazy-loading would delay it and hurt LCP instead
    of helping.
--}}
@props(['src' => null, 'srcset' => null, 'sizes' => null, 'alt' => '', 'eager' => false])
@if ($src)
    <img
        src="{{ $src }}"
        @if ($srcset) srcset="{{ $srcset }}" @endif
        @if ($sizes) sizes="{{ $sizes }}" @endif
        alt="{{ $alt }}"
        loading="{{ $eager ? 'eager' : 'lazy' }}"
        {{ $attributes }}
    />
@else
    <div {{ $attributes }}></div>
@endif
